In [1]:
import urllib.request
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
result = []

for page in range(1, 39):
    stock_url = "https://finance.naver.com/sise/sise_market_sum.naver?&page=%d" % page


    html = urllib.request.urlopen(stock_url)
    soupStock = BeautifulSoup(html, "html.parser",from_encoding="euc-kr")
    tag_tbody = soupStock.find("tbody")
    for stock in tag_tbody.find_all("tr",onmouseover="mouseOver(this)"):
        # if len(stock) <= 11:
        #     break
        stock_td = stock.find_all("td")
        stock_title = stock_td[1].string
        stock_price = stock_td[2].string
        stock_yesterday = stock_td[3].find("span").string.strip("\n""\t")
        stock_updown = stock_td[4].find("span").string.strip("\n""\t")
        stock_perPrice = stock_td[5].string
        stock_total = stock_td[6].string
        stock_value = stock_td[7].string
        stock_foreign = stock_td[8].string
        stock_trades = stock_td[9].string
        stock_PER = stock_td[10].string
        stock_ROE = stock_td[11].string
        
        result.append(
            [stock_title]
            + [stock_price]
            + [stock_yesterday]
            + [stock_updown]
            + [stock_perPrice]
            + [stock_total]
            + [stock_value]
            + [stock_foreign]
            + [stock_trades]
            + [stock_PER]
            + [stock_ROE]
        )

In [3]:
stock_td = pd.DataFrame(result, columns=("종목명","현재가","전일비","등략률","액면가","시가총액","상장주식수","외국인비율","거래량","PER","ROE"))

In [4]:
stock_td

,종목명,현재가,전일비,등략률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE
0,삼성전자,"56,000",300,-0.53%,100,"3,343,078","5,969,783",49.52,"3,623,596",8.49,13.92
1,LG에너지솔루션,"483,500",500,+0.10%,500,"1,131,390","234,000",4.50,"45,189",803.16,10.68
2,SK하이닉스,"94,500","1,000",-1.05%,"5,000","687,962","728,002",50.84,"535,017",5.99,16.84
3,삼성바이오로직스,"805,000","1,000",-0.12%,"2,500","572,951","71,174",10.49,"5,661",107.06,8.21
4,삼성전자우,"51,000",400,-0.78%,100,"419,672","822,887",71.62,"223,993",7.74,N/A
...,...,...,...,...,...,...,...,...,...,...,...
1884,KBSTAR 200경기소비재,"8,470",110,-1.28%,0,7,80,0.00,4,N/A,N/A
1885,신한 레버리지 코스피 200 선물 ETN,"19,985",0,0.00%,0,0,"1,000",0.00,0,N/A,N/A
1886,신한 레버리지 코스닥 150 선물 ETN,"19,875",0,0.00%,0,0,"2,500",0.00,0,N/A,N/A
1887,하나 레버리지 코스닥150 선물 ETN,"19,875",0,0.00%,0,0,"1,000",0.00,0,N/A,N/A
1888,하나 인버스 2X 코스닥150 선물 ETN,"19,810",0,0.00%,0,0,"1,000",0.00,0,N/A,N/A

In [5]:
stock_td.to_csv("stock_test.csv",encoding="UTF-8",mode="w",index=True)